export const allOrderList=[
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires: 6 ,
        shipping:'ABC Plant',
        createdBy: 'Created by John',
        status:'',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires: 90 ,
        shipping:'ABC Plant',
        createdBy: 'Created by John',
        status:'new',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires:2 ,
        shipping:'Russia Plant',
        createdBy: 'Created by John',
        status:'',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires: 90 ,
        shipping:'ABC Plant',
        createdBy: 'Created by John',
        status:'new',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires: 90 ,
        shipping:'Russia Plant',
        createdBy: 'Created by John',
        status:'new',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires: 5 ,
        shipping:'Russia Plant',
        createdBy: 'Created by John',
        // status:'new',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires: 90 ,
        shipping:'Russia Plant',
        createdBy: 'Created by John',
        status:'new',
    },
   
]