export const allOrderList=[
    [{
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires: 6 ,
        shipping:'ABC Plant',
        createdBy: 'Created by John',
        status:'',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:`10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE`,
        expires: 90 ,
        shipping:'ABC Plant',
        createdBy: 'Created by John',
        status:'new',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'Canyon Ridge® Collection Ultra-Grain® Series with Intellicore®',
        expires:2 ,
        shipping:'Russia Plant',
        createdBy: 'Created by John',
        status:'',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'Hardware Special - Stock. W4.HB.8.0.7.0.None.Sol - WH.9.G.2J.B..S',
        expires: 90 ,
        shipping:'ABC Plant',
        createdBy: 'Created by John',
        status:'new',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'8’ 8’’ X 8’ 6’’ CAN211CCW1 Commercial DOOR INTELLICORE',
        expires: 90 ,
        shipping:'Russia Plant',
        createdBy: 'Created by John',
        status:'new',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires: 5 ,
        shipping:'Russia Plant',
        createdBy: 'Created by John',
        // status:'new',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires: 90 ,
        shipping:'Russia Plant',
        createdBy: 'Created by John',
        status:'new',
    },],
    [
        {
            groupName:'Classic_Johnson1456',
            refNo:'#42521983',
            title:'2 Classic Collection Garage Door, 2 Entry Door',
            expires: 5 ,
            shipping:'Russia Plant',
            createdBy: 'Created by John',
            // status:'new',
        },
        {
            groupName:'Classic_Johnson1456',
            refNo:'#42521983',
            title:'2 Classic Collection Garage Door, 2 Entry Door',
            expires: 90 ,
            shipping:'Russia Plant',
            createdBy: 'Created by John',
            status:'new',
        },
        {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires: 6 ,
        shipping:'ABC Plant',
        createdBy: 'Created by John',
        status:'',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires: 90 ,
        shipping:'ABC Plant',
        createdBy: 'Created by John',
        status:'new',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires:2 ,
        shipping:'Russia Plant',
        createdBy: 'Created by John',
        status:'',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires: 90 ,
        shipping:'ABC Plant',
        createdBy: 'Created by John',
        status:'new',
    },
    {
        groupName:'Classic_Johnson1456',
        refNo:'#42521983',
        title:'2 Classic Collection Garage Door, 2 Entry Door',
        expires: 90 ,
        shipping:'Russia Plant',
        createdBy: 'Created by John',
        status:'new',
    },
    ],
   
]